- name: Configure kubernetes cluster
  hosts: localhost
  vars_files: ../env_variables_aws.yaml
  tasks:
    - name: Prepare reusable fact
      ansible.builtin.set_fact:
        terraform_outputs: "{{ root.outputs.location }}/{{ root.terraform.prefix }}"

    - name: Check if success file exists
      ansible.builtin.stat:
        path: "{{ terraform_outputs }}/success"
      register: success_file

    - name: Set fact
      ansible.builtin.set_fact:
        success_file_exists: "{{ success_file.stat.exists }}"

- name: Reset kubernetes cluster for idempotency
  hosts: masters:workers
  vars_files: ../env_variables_aws.yaml
  tasks:
    - name: Ensure reset kubernetes cluster 
      shell: |
        hostnamectl set-hostname $(curl http://169.254.169.254/latest/meta-data/local-hostname)
        kubeadm reset -f --cri-socket unix:///var/run/crio/crio.sock
      become: true
      ignore_errors: true
      when: hostvars['localhost']['success_file_exists']

    - name: Ensure reset kubernetes cluster 
        rm -rf /etc/kubernetes/* 2> /dev/null
        rm -rf /var/lib/etcd 2> /dev/null
        rm -rf /etc/apt/sources.list.d/* 2> /dev/null
        rm -rf /var/lib/cni/ 2> /dev/null
        rm -rf /var/lib/kubelet/* 2> /dev/null
        rm -rf /etc/cni/ 2> /dev/null
        ifconfig cni0 down 2> /dev/null
        ip link delete cni0 2> /dev/null
        ip link delete flannel.1 2> /dev/null
        ip link delete vxlan.calico 2> /dev/null
        ifconfig flannel.1 down 2> /dev/null
        ifconfig vxlan.calico down 2> /dev/null
        ifconfig docker0 down 2> /dev/null
        systemctl daemon-reload 2> /dev/null
        systemctl restart crio 2> /dev/null
        systemctl enable crio 2> /dev/null
        systemctl stop kubelet 2> /dev/null
        systemctl stop docker 2> /dev/null
      become: true
      ignore_errors: true
      when: hostvars['localhost']['success_file_exists']

- name: Import playbook
  ansible.builtin.import_playbook: install_dependencies.yaml
  when: hostvars['localhost']['success_file_exists']

- name: Import playbook
  ansible.builtin.import_playbook: initialize_master.yaml
  when: hostvars['localhost']['success_file_exists']

- name: Import playbook
  ansible.builtin.import_playbook: join_workers.yaml
  when: hostvars['localhost']['success_file_exists']

- name: Install kubernetes resources
  hosts: localhost
  vars_files: ../env_variables_aws.yaml
  tasks:
    - name: Prepare reusable fact
      ansible.builtin.set_fact:
        terraform_outputs: "{{ root.outputs.location }}/{{ root.terraform.prefix }}"
        kubeconfig: "--kubeconfig {{ terraform_outputs }}/kubeconfig"
        subnet_name: "{{ root.terraform.prefix | normalize_string | concat_strings(resources.subnet.options.name) }}"

    - name: Install aws
      ansible.builtin.include_tasks:
        file: dependencies/aws.yml
      when: utils.aws.enabled

    - name: Import playbook storage class
      ansible.builtin.include_tasks: kubernetes_resources/storage_class.yaml
      when: hostvars['localhost']['success_file_exists']
