- name: Check if target variable is in accepted ones
  set_fact:
    ubuntu_target: "{{ target in ['ubuntu_22_04', 'ubuntu_20_04', 'ubuntu_23_10'] }}"

- name: Install specific Python3 version
  apt:
    name: "python{{ utils.python.version }}"
    state: present
  become: true
  when: ubuntu_target
  register: result
  ignore_errors: true

- name: Install Python3 if specific version is not available
  apt:
    name: python3
    state: present
  become: true
  when: ubuntu_target and result.failed

- name: Install pip
  apt:
    name: python3-pip
    state: present
  become: true
  when: ubuntu_target

- name: Upgrade pip
  shell: |
    python3 -m pip install --upgrade pip
  when: ubuntu_target

- name: Install pipenv
  shell: |
    sudo -H pip3 install pipenv
  become: true
  when: ubuntu_target
